### ISSUE TITLE
chore(general): CircleCI fails to build the project

### ISSUE THREAD

**Issue by MacZel** [MacZel/Nuxt-Nest-Monorepo#45]
Lerna fails at bootstrap step with following exit log:
```
> root@ bootstrap /home/circleci/repo
> lerna bootstrap

lerna notice cli v3.13.1
lerna info ci enabled
lerna info Bootstrapping 4 packages
lerna info Installing external dependencies
lerna ERR! npm ci exited 244 in '@vanad/styleguide'
lerna ERR! npm ci stderr:
WARN tar ENOMEM: not enough memory, open '/home/circleci/repo/packages/styleguide/node_modules/websocket-extensions/LICENSE.md'
npm ERR! code ENOMEM
npm ERR! errno -12
npm ERR! syscall read
npm ERR! ENOMEM: not enough memory, read

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-03-06T22_08_02_990Z-debug.log

lerna ERR! npm ci exited 244 in '@vanad/styleguide'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 244
npm ERR! root@ bootstrap: `lerna bootstrap`
npm ERR! Exit status 244
npm ERR! 
npm ERR! Failed at the root@ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-03-06T22_08_03_144Z-debug.log
Exited with code 244
```
Will try to limit max concurrency with command `lerna bootstrap --concurrency=2`

**Comment by MacZel** [comment]
After this change this process is being run correctly.
Another issue that came out is CircleCI not being able to launch browser testing with puppeteer.
exit log:
```
> root@ test /home/circleci/repo
> lerna run test

lerna notice cli v3.13.1
lerna info ci enabled
lerna info Executing command in 2 packages: "npm run test"
lerna ERR! npm run test exited 1 in '@vanad/app'
lerna ERR! npm run test stdout:

> @vanad/app@0.0.1 test /home/circleci/repo/packages/app
> npm-run-all --sequential test:*


> @vanad/app@0.0.1 test:e2e /home/circleci/repo/packages/app
> cross-env JEST_PUPPETEER_CONFIG=config/jest/puppeteer.js jest --config=config/jest/e2e.json


lerna ERR! npm run test stderr:
Error: Failed to launch chrome!
/home/circleci/repo/packages/app/node_modules/puppeteer/.local-chromium/linux-624487/chrome-linux/chrome: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/circleci/repo/packages/app/node_modules/puppeteer/lib/Launcher.js:360:14)
    at Interface.helper.addEventListener (/home/circleci/repo/packages/app/node_modules/puppeteer/lib/Launcher.js:349:50)
    at Interface.emit (events.js:194:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vanad/app@0.0.1 test:e2e: `cross-env JEST_PUPPETEER_CONFIG=config/jest/puppeteer.js jest --config=config/jest/e2e.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @vanad/app@0.0.1 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-03-06T22_19_35_592Z-debug.log
ERROR: "test:e2e" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vanad/app@0.0.1 test: `npm-run-all --sequential test:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @vanad/app@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-03-06T22_19_35_603Z-debug.log

lerna ERR! npm run test exited 1 in '@vanad/app'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! root@ test: `lerna run test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the root@ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-03-06T22_19_35_619Z-debug.log
Exited with code 1
```
Will try to change docker image from node:10 to node:latest-browsers

**Comment by MacZel** [comment]
Seems related to [issue](https://github.com/smooth-code/jest-puppeteer/issues/200)
Temporarily disable e2e tests in app.
